### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ohmez** [ohmez/GroupProject#2]
## Some Story in bold
Here is general text.
## Acceptance Criteria - bold
- [x] You understand this
- [ ] you want to learn
- [ ] you checked this

**Comment by zevans98** [comment]
##howdy
story nonsense
- [ ] check me

**Comment by JonathonBeeBaker** [comment]
## user wants to plan a list of destinations and hit them in a certain order and know how long each trip will take. 
- [] create a list that can be added to
- [] connect to Google maps to route the destinations.

**Comment by libbyrae89** [comment]
**To Do**

- Go home now and take a nap.
